{den, ...}: {
  # Shared developer tooling aspect — packages and programs used on both
  # mahakala (Linux workstation) and M-02877 (macOS work machine).
  # Host-specific additions go in workstation.nix or dktaohan.nix.
  den.aspects.sharedDevtools = {
    includes = [den.aspects.devtools];
    homeManager = {
      pkgs,
      lib,
      ...
    }: {
      home.packages = with pkgs;
        [
          nodejs
          bun
          uv
          kubectl
          shellcheck
          yq-go
          glab
          just
          bash-preexec
          claude-code
          pi
          bv
          mcp-agent-mail
        ]
        ++ lib.optionals (!pkgs.stdenv.hostPlatform.isDarwin) [
          rtk
          decapod
          br
        ];

      programs.github-copilot-cli.enable = true;
      programs.direnv = {
        enable = true;
        nix-direnv.enable = true;
      };

      programs.eza.enable = true;
      programs.bat.enable = true;
      programs.zoxide.enable = true;
      programs.jq.enable = true;

      programs.atuin = {
        enable = true;
        settings = {
          auto_sync = lib.mkDefault true;
          sync_frequency = "5m";
          search_mode = "fuzzy";
        };
      };

      programs.k9s.enable = true;

      # Guix Home owns ~/.bashrc on mahakala, so Home Manager cannot inject
      # Bash init snippets directly. Export one sourceable fragment instead.
      # bash-preexec must load before Atuin/Starship; zoxide stays last.
      home.file.".config/bash/home-manager-integrations.bash".text = ''
                # Generated by Home Manager. Sourced from Guix Home's ~/.bashrc.
                # shellcheck shell=bash
                [[ $- == *i* ]] || return

                if command -v direnv >/dev/null 2>&1; then
                  eval "$(direnv hook bash)"
                fi

                _hm_bash_preexec="${pkgs.bash-preexec}/share/bash/bash-preexec.sh"
                # shellcheck source=/dev/null
                [[ -r "$_hm_bash_preexec" ]] && source "$_hm_bash_preexec"
                unset _hm_bash_preexec

                if command -v atuin >/dev/null 2>&1; then
                  eval "$(atuin init bash)"
                fi

                if command -v starship >/dev/null 2>&1; then
                  eval "$(starship init bash)"
                fi

                if command -v fzf >/dev/null 2>&1; then
                  eval "$(fzf --bash)"
                fi

                _openclaw_redact_secrets() {
                  sed -E 's/sk-[A-Za-z0-9_-]+/[REDACTED]/g'
                }

                openclaw-auth-loving-kypris() {
                  local host="loving-kypris"
                  local tmux_session="openclaw-openai-auth"
                  local log_path="/tmp/openclaw-openai-auth.log"
                  local auth_url="https://auth.openai.com/codex/device"
                  local code=""
                  local tries=0
                  local script_b64=""

                  # Compatibility shim: OpenClaw harness still looks up legacy
                  # openai-codex:default even after doctor migrates canonical profiles to
                  # openai:<email>. Copy alias from canonical OAuth profile; remove when
                  # upstream no longer requires the legacy profile id.
                  local -r _openclaw_codex_alias_js='const { DatabaseSync } = require("node:sqlite");
        const path = require("node:path");
        const os = require("node:os");
        const dbPath = path.join(os.homedir(), ".openclaw/agents/main/agent/openclaw-agent.sqlite");
        let db;
        try {
          db = new DatabaseSync(dbPath);
        } catch (err) {
          console.log("openclaw alias: cannot open auth store:", err.message);
          process.exit(0);
        }
        const row = db.prepare("SELECT * FROM auth_profile_store WHERE store_key = ?").get("primary");
        if (!row) {
          console.log("openclaw alias: no primary auth store row; skipping");
          process.exit(0);
        }
        const valueCol = ["store_json", "value", "data", "store_value"].find((col) => row[col] !== undefined);
        if (!valueCol) {
          console.log("openclaw alias: primary row has no JSON payload column; skipping");
          process.exit(0);
        }
        let store;
        try {
          store = JSON.parse(row[valueCol]);
        } catch (_err) {
          console.log("openclaw alias: invalid JSON in primary store; skipping");
          process.exit(0);
        }
        const profiles = store.profiles || {};
        if (profiles["openai-codex:default"] && profiles["openai-codex:default"].type === "oauth") {
          console.log("openclaw alias: openai-codex:default OAuth profile already present; skipping");
          process.exit(0);
        }
        const sourceId = Object.keys(profiles).find(
          (id) =>
            id.startsWith("openai:") &&
            id !== "openai-codex:default" &&
            profiles[id] &&
            profiles[id].type === "oauth",
        );
        if (!sourceId) {
          console.log("openclaw alias: no canonical openai:* OAuth profile; skipping");
          process.exit(0);
        }
        profiles["openai-codex:default"] = JSON.parse(JSON.stringify(profiles[sourceId]));
        store.profiles = profiles;
        const setParts = [valueCol + " = ?"];
        const params = [JSON.stringify(store)];
        if (row.updated_at !== undefined) {
          setParts.push("updated_at = ?");
          params.push(Date.now());
        }
        params.push("primary");
        db.prepare("UPDATE auth_profile_store SET " + setParts.join(", ") + " WHERE store_key = ?").run(...params);
        console.log("openclaw alias: copied OAuth profile " + sourceId + " -> openai-codex:default");'

                  _openclaw_auth_cleanup() {
                    ssh -q "$host" \
                      "tmux kill-session -t '$tmux_session' 2>/dev/null || true; rm -f '$log_path'"
                  }

                  _openclaw_ensure_codex_alias() {
                    script_b64=$(
                      printf '%s' "$_openclaw_codex_alias_js" | base64 -w0 2>/dev/null \
                        || printf '%s' "$_openclaw_codex_alias_js" | base64 | tr -d '\n'
                    )
                    ssh -q "$host" \
                      "podman exec openclaw-gateway sh -lc 'echo \"$script_b64\" | base64 -d > /tmp/openclaw-codex-alias.mjs && node /tmp/openclaw-codex-alias.mjs; rm -f /tmp/openclaw-codex-alias.mjs'"
                  }

                  trap '_openclaw_auth_cleanup' RETURN

                  if ! ssh -q "$host" \
                    "systemctl --user is-active --quiet openclaw-gateway || systemctl --user start openclaw-gateway"; then
                    echo "openclaw-auth-loving-kypris: failed to ensure openclaw-gateway is active on $host" >&2
                    return 1
                  fi

                  _openclaw_auth_cleanup

                  if ! ssh -q "$host" \
                    "tmux new-session -d -s '$tmux_session' \"podman exec -it openclaw-gateway sh -lc 'cd /app && node /app/openclaw.mjs models auth login --provider openai --device-code --force' 2>&1 | tee '$log_path'\""; then
                    echo "openclaw-auth-loving-kypris: failed to start remote auth session" >&2
                    return 1
                  fi

                  while [[ -z "$code" && $tries -lt 60 ]]; do
                    sleep 2
                    code=$(
                      ssh -q "$host" "grep -E 'Code:' '$log_path' 2>/dev/null | tail -1" \
                        | sed -n 's/.*Code:[[:space:]]*\([A-Z0-9-]*\).*/\1/p'
                    )
                    tries=$((tries + 1))
                  done

                  if [[ -z "$code" ]]; then
                    echo "openclaw-auth-loving-kypris: timed out waiting for device code in $log_path" >&2
                    ssh -q "$host" "cat '$log_path' 2>/dev/null" | _openclaw_redact_secrets >&2
                    return 1
                  fi

                  echo "OpenAI Codex device auth"
                  echo "URL:  $auth_url"
                  echo "Code: $code"
                  if command -v xdg-open >/dev/null 2>&1; then
                    xdg-open "$auth_url"
                  fi
                  read -r -p "Press Enter after completing auth in the browser..."

                  echo "Waiting for OAuth completion..."
                  sleep 5

                  echo "Ensuring legacy openai-codex:default alias..."
                  _openclaw_ensure_codex_alias

                  echo "Restarting openclaw-gateway..."
                  if ! ssh -q "$host" "systemctl --user restart openclaw-gateway"; then
                    echo "openclaw-auth-loving-kypris: failed to restart openclaw-gateway on $host" >&2
                    return 1
                  fi
                  sleep 3

                  echo "Verifying OpenAI auth..."
                  ssh -q "$host" \
                    "podman exec openclaw-gateway sh -lc 'cd /app && node /app/openclaw.mjs models auth list --provider openai'" \
                    | _openclaw_redact_secrets
                  ssh -q "$host" \
                    "podman exec openclaw-gateway sh -lc 'cd /app && node /app/openclaw.mjs models status --probe --probe-provider openai --probe-timeout 30000 --probe-concurrency 1'" \
                    | _openclaw_redact_secrets

                  echo "Recent gateway auth signals:"
                  ssh -q "$host" \
                    "journalctl --user -u openclaw-gateway -n 200 --no-pager" \
                    | grep -E 'openai-codex:default|insufficient_quota|subscription usage limit|auth profile|gpt-5.5|Codex app-server' \
                    | _openclaw_redact_secrets \
                    || true
                }

                if command -v zoxide >/dev/null 2>&1; then
                  eval "$(zoxide init bash)"
                fi
      '';

      # Pi configuration lives in modules/pi.nix
    };
  };
}
