{den, ...}: {
  # Shared developer tooling aspect — packages and programs used on both
  # mahakala (Linux workstation) and M-02877 (macOS work machine).
  # Host-specific additions go in workstation.nix or dktaohan.nix.
  den.aspects.sharedDevtools = {
    includes = [den.aspects.devtools];
    homeManager = {
      pkgs,
      lib,
      ...
    }: {
      home.packages = with pkgs; [
        nodejs
        bun
        uv
        kubectl
        shellcheck
        yq-go
        glab
        just
        bash-preexec
        claude-code
        pi
        rtk
        decapod
        br
        bv
        mcp-agent-mail
      ];

      programs.github-copilot-cli.enable = true;
      programs.direnv = {
        enable = true;
        nix-direnv.enable = true;
      };

      programs.eza.enable = true;
      programs.bat.enable = true;
      programs.zoxide.enable = true;
      programs.jq.enable = true;

      programs.atuin = {
        enable = true;
        settings = {
          auto_sync = lib.mkDefault true;
          sync_frequency = "5m";
          search_mode = "fuzzy";
        };
      };

      programs.k9s.enable = true;

      # Guix Home owns ~/.bashrc on mahakala, so Home Manager cannot inject
      # Bash init snippets directly. Export one sourceable fragment instead.
      # bash-preexec must load before Atuin/Starship; zoxide stays last.
      home.file.".config/bash/home-manager-integrations.bash".text = ''
        # Generated by Home Manager. Sourced from Guix Home's ~/.bashrc.
        # shellcheck shell=bash
        [[ $- == *i* ]] || return

        if command -v direnv >/dev/null 2>&1; then
          eval "$(direnv hook bash)"
        fi

        _hm_bash_preexec="${pkgs.bash-preexec}/share/bash/bash-preexec.sh"
        # shellcheck source=/dev/null
        [[ -r "$_hm_bash_preexec" ]] && source "$_hm_bash_preexec"
        unset _hm_bash_preexec

        if command -v atuin >/dev/null 2>&1; then
          eval "$(atuin init bash)"
        fi

        if command -v starship >/dev/null 2>&1; then
          eval "$(starship init bash)"
        fi

        if command -v fzf >/dev/null 2>&1; then
          eval "$(fzf --bash)"
        fi

        if command -v zoxide >/dev/null 2>&1; then
          eval "$(zoxide init bash)"
        fi
      '';

      # Pi configuration lives in modules/pi.nix
    };
  };
}
