/**
 * LEGO AI Model Gateway provider extension for Pi.
 *
 * The gateway is a faithful Anthropic Messages passthrough, so this registers
 * against pi's built-in `anthropic-messages` API rather than shipping a custom
 * `streamSimple`. That matters for more than tidiness: a custom `api` string can
 * only be resolved on pi's session stream path. Anything using pi's default
 * stream function — subagents and background tasks — calls `resolveApiProvider`,
 * which only knows built-in APIs, and an unknown api there throws an
 * uncaught exception that takes the whole process down mid-session.
 *
 * Auth is `Authorization: Bearer <vk_...>`, which `authHeader` adds from the
 * resolved key. The key itself is fetched from the macOS keychain at runtime by
 * the `!secretspec get` command below and is never written to disk.
 *
 * Models come from models.json, generated by Home Manager so the tier mapping
 * and the model catalogue share a single source.
 */

import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// pi loads extensions through jiti, which does not reliably give this module its
// own directory via import.meta.url — under the bun binary __dirname can resolve
// to the nix store root. So try the module-relative path first and fall back to
// the known install location rather than trusting the loader.
const MODELS_FILENAME = "models.json";
const INSTALL_DIR = join(homedir(), ".pi/agent/extensions/anthropic-proxy");

function moduleDir() {
  try {
    return dirname(fileURLToPath(import.meta.url));
  } catch {
    return undefined;
  }
}

function modelsPathCandidates() {
  const dir = moduleDir();
  return [...new Set([dir && join(dir, MODELS_FILENAME), join(INSTALL_DIR, MODELS_FILENAME)])].filter(
    Boolean
  );
}

const BASE_URL =
  process.env.PI_ANTHROPIC_BASE_URL || "https://api.genai.thelegogroup.com/anthropic";

const SECRETSPEC_MANIFEST = "/Users/dktaohan/.config/home-manager/secretspec.toml";
const API_KEY_COMMAND = `!secretspec get -f ${SECRETSPEC_MANIFEST} LEGO_GATEWAY_API_KEY`;

export function loadModels(candidates = modelsPathCandidates()) {
  let raw;
  for (const path of candidates) {
    try {
      raw = readFileSync(path, "utf-8");
      break;
    } catch (err) {
      if (err.code !== "ENOENT") throw err;
    }
  }

  if (raw === undefined) {
    console.warn(
      `[anthropic-proxy] No ${MODELS_FILENAME} found in: ${candidates.join(", ")} — provider will have no models.`
    );
    return [];
  }

  const models = JSON.parse(raw);
  if (!Array.isArray(models)) {
    console.warn("[anthropic-proxy] models.json must be a JSON array, got:", typeof models);
    return [];
  }

  return models.filter((m, i) => {
    if (!m.id || !m.name) {
      console.warn(`[anthropic-proxy] models.json[${i}] missing id or name — skipping`);
      return false;
    }
    for (const field of ["maxTokens", "contextWindow"]) {
      if (typeof m[field] !== "number" || m[field] <= 0) {
        console.warn(`[anthropic-proxy] models.json[${i}] "${field}" must be positive — skipping`);
        return false;
      }
    }
    return true;
  });
}

export function buildProviderConfig(models) {
  return {
    name: "LEGO AI Model Gateway",
    baseUrl: BASE_URL,
    apiKey: API_KEY_COMMAND,
    api: "anthropic-messages",
    authHeader: true,
    models,
  };
}

export default function (pi) {
  const models = loadModels();
  console.log(`[anthropic-proxy] Loaded ${models.length} model(s) from models.json`);
  pi.registerProvider("anthropic-proxy", buildProviderConfig(models));
}
