{
  # Team integrations for the agents on this work Mac: Chorus, Beads, team
  # Signet and the LEGO TechWriter docs toolbox. M-02877 only; the personal
  # machines keep their own Signet and have no LEGO access.
  den.aspects.dktaohan.homeManager = {
    pkgs,
    lib,
    config,
    ...
  }: let
    home = config.home.homeDirectory;

    # Team Chorus: LEGO/devrel-infra projects/aws-chorus, reached through the
    # chorus-team-tunnel launchd agent (darwin.nix) on 3870. Since
    # devrel-infra#280 it has no load balancer or DNS name; its NEXTAUTH_URL is
    # http://127.0.0.1:3870, so the web login works only on this port. Server,
    # client and chorus-pi are all Chorus 0.21.1 (server since devrel-infra#291,
    # 2026-10-07); 0.21.1 is the first release with pi's built-in MCP (Chorus
    # #597, #598). devrel-infra's nightly release job proposes server upgrades;
    # move chorusVersion with them.
    chorusUrl = "http://127.0.0.1:3870";
    chorusVersion = "0.21.1";

    # Team Signet: LEGO/devrel-infra projects/aws-signet, reached through the
    # signet-team-tunnel launchd agent (darwin.nix) on 3860. The key is the one
    # projects/aws-signet scripts/enroll.sh issued, and its scope is the agent
    # id derived from the enrolling email; every write must send that id, so
    # an unset SIGNET_AGENT_ID ("default") is refused.
    signetEnv = {
      SIGNET_DAEMON_URL = "http://127.0.0.1:3860";
      SIGNET_AGENT_ID = "tao.hansen";
    };
    signetTokenFile = "${home}/.config/signet/token";

    # LEGO/agentic-engineering-community, plugins/toolbox-docs. The repo is
    # internal and this flake is public, so it cannot be a flake input (the
    # lock would publish the rev, and the personal hosts could not fetch it).
    # Activation clones this one rev with gh's credential instead.
    toolboxDocsRev = "6a46c9f9c7d78b9c379b4c1d2fd00261c8e3bee6";
    toolboxDocsSkills = [
      "diataxis"
      "simple-english"
      "rewrite-slop"
      "rewrite-documentation"
      "write-usecase"
      "edit-confluence-page"
    ];

    # The techwriter agent is written for Copilot. pi's subagent tool (bundled
    # in chorus-pi) reads ~/.pi/agent/agents/*.md, so this keeps its body and
    # swaps the Copilot frontmatter for pi's.
    techwriterHeader = pkgs.writeText "techwriter-header.md" ''
      ---
      name: techwriter
      description: LEGO documentation contributor. Writes and edits Markdown documentation to the LEGO Writing Style Guide, which it first fetches from the LEGO "Technical Writer" Copilot Space. Generated by home-manager from LEGO/agentic-engineering-community plugins/toolbox-docs at ${toolboxDocsRev}; edits are overwritten.
      tools: read, grep, find, ls, bash, edit, write, codemode, tool_search
      ---

      In pi, the Copilot Space tool `githubspacesmcp/get_copilot_space` is
      `mcp__github_spaces__get_copilot_space` (call it with owner `LEGO` and
      name `Technical Writer`). If it is not available, use the GitHub CLI
      route described below. The toolbox-docs skills `diataxis`,
      `simple-english` and `rewrite-slop` are installed; use them in the order
      the toolbox README gives.

    '';

    # The Chorus daemon wakes a headless `pi --mode rpc` when work is sent to
    # this agent from Chorus. launchd starts it without a login shell, so it
    # gets the environment an interactive pi would have: PATH, Chorus and team
    # Signet. pi's own gateway credential is a `!command` in models.json.
    chorusPiDaemon = pkgs.writeShellApplication {
      name = "chorus-pi-daemon";
      runtimeInputs = [pkgs.coreutils];
      text = ''
        export PATH="/etc/profiles/per-user/${config.home.username}/bin:${home}/.local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        export CHORUS_URL=${chorusUrl}
        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (n: v: "export ${n}=${lib.escapeShellArg v}") signetEnv)}
        SIGNET_API_KEY="$(cat ${lib.escapeShellArg signetTokenFile} 2>/dev/null || true)"
        export SIGNET_API_KEY
        # secretspec's Secure Enclave identity refuses to decrypt while the
        # screen is locked (errSecInteractionNotAllowed, -25308), and this
        # daemon exists to be woken while nobody is at the Mac. So, like the
        # gateway keyCommand (modules/gateway.nix), a good read refreshes a
        # 0600 cache and a failed one falls back to it.
        cache=${lib.escapeShellArg "${home}/.local/state/chorus-api-key.cache"}
        if CHORUS_API_KEY="$(secretspec get -f ${lib.escapeShellArg "${home}/.config/home-manager/secretspec.toml"} CHORUS_API_KEY --reason "Chorus pi daemon")" && [ -n "$CHORUS_API_KEY" ]; then
          if ! printf '%s\n' "$CHORUS_API_KEY" | cmp -s - "$cache"; then
            (umask 077 && printf '%s\n' "$CHORUS_API_KEY" >"$cache.$$" && mv "$cache.$$" "$cache")
          fi
        elif [ -s "$cache" ]; then
          echo "chorus-pi-daemon: secretspec unavailable (screen locked?); using the cached key" >&2
          CHORUS_API_KEY="$(cat "$cache")"
        else
          # Fail slowly: launchd restarts after ThrottleInterval, so a missing
          # key costs one wait per minute rather than a hot loop.
          echo "chorus-pi-daemon: CHORUS_API_KEY unavailable from secretspec and no cache; retrying" >&2
          sleep 60
          exit 1
        fi
        export CHORUS_API_KEY
        if ! command -v chorus >/dev/null; then
          echo "chorus-pi-daemon: chorus CLI not installed yet; retrying" >&2
          sleep 60
          exit 1
        fi
        # A woken pi gets the file access of this user in every served
        # directory, so the served set is deliberately just ~/projects.
        # The browse root defaults to $HOME, which lists every directory
        # name under it to the team server; keep discovery to ~/projects too.
        exec chorus daemon --agent pi --cwd ${lib.escapeShellArg "${home}/projects"} \
          --browse-root ${lib.escapeShellArg "${home}/projects"}
      '';
    };
  in {
    home.sessionVariables =
      signetEnv
      // {
        # Evaluated when hm-session-vars.sh is sourced, so the key is read
        # from the file setup.sh wrote and never lands in the Nix store.
        SIGNET_API_KEY = "$(cat ${signetTokenFile} 2>/dev/null)";
      };

    piAgent = {
      mcpServers = {
        # Native MCP defaults to codemode, which chorus-pi expects.
        chorus = {
          url = "${chorusUrl}/api/mcp";
          headers.Authorization = "Bearer \${CHORUS_API_KEY}";
          description = "Team Chorus AI-DLC: ideas, proposals, tasks and reviews";
        };
        # Copilot Spaces only (the /x/ toolset path), for the techwriter agent.
        # gh's OAuth token is accepted; no PAT.
        github-spaces = {
          url = "https://api.githubcopilot.com/mcp/x/copilot_spaces";
          headers.Authorization = "!echo Bearer $(gh auth token)";
          exposure = "direct";
          description = "GitHub Copilot Spaces, including LEGO's Technical Writer style guide";
        };
      };
      packages = [
        "npm:@chorus-aidlc/chorus-pi@${chorusVersion}"
        # Agent side of Beads: `bd prime` in the system prompt and kept
        # through compaction, plus /beads:* commands. Only ever runs `bd`.
        "npm:pi-beads-extension@0.1.0"
        # Human side: a task browser (/tasks, ctrl+shift+r, alt+x) over the
        # same bd backend.
        "npm:@soleone/pi-tasks@0.5.0"
      ];
    };

    home.activation = {
      # The chorus CLI is the whole Chorus app (Next.js server included), so
      # it is installed from npm, pinned, rather than packaged in Nix.
      chorusCli = lib.hm.dag.entryAfter ["writeBoundary"] ''
        if [ "$(${home}/.local/bin/chorus --version 2>/dev/null || true)" != ${chorusVersion} ]; then
          PATH=${lib.makeBinPath [pkgs.nodejs]}:$PATH NPM_CONFIG_PREFIX=${home}/.local \
            run npm install -g --no-fund --no-audit @chorus-aidlc/chorus@${chorusVersion} ||
            warnEcho "chorus: could not install @chorus-aidlc/chorus@${chorusVersion}; the next switch retries"
        fi
      '';

      # Replaces the hand-copied skills in ~/.agents/skills, which every
      # harness links to, with the toolbox-docs ones. A replaced directory is
      # moved to ~/.agents/skills-replaced/, never deleted.
      toolboxDocs = lib.hm.dag.entryAfter ["writeBoundary"] ''
        rev=${toolboxDocsRev}
        root=${home}/.local/share/toolbox-docs
        dir="$root/$rev"
        if [ ! -d "$dir/plugins/toolbox-docs" ]; then
          tmp="$root/.clone-$rev"
          run rm -rf "$tmp"
          run mkdir -p "$root"
          if PATH=${lib.makeBinPath [pkgs.git pkgs.gh]}:$PATH run git \
              -c credential.helper= -c 'credential.helper=!gh auth git-credential' \
              clone -q --filter=blob:none --no-checkout \
              https://github.com/LEGO/agentic-engineering-community "$tmp" &&
            run ${lib.getExe pkgs.git} -C "$tmp" sparse-checkout set plugins/toolbox-docs &&
            run ${lib.getExe pkgs.git} -C "$tmp" checkout -q "$rev"; then
            run mv "$tmp" "$dir"
          else
            run rm -rf "$tmp"
            warnEcho "toolbox-docs: could not fetch LEGO/agentic-engineering-community@$rev; the next switch retries"
          fi
        fi
        if [ -d "$dir/plugins/toolbox-docs" ]; then
          src="$dir/plugins/toolbox-docs"
          for s in ${lib.escapeShellArgs toolboxDocsSkills}; do
            link="${home}/.agents/skills/$s"
            if [ -L "$link" ]; then
              [ "$(readlink "$link")" = "$src/skills/$s" ] || run ln -sfn "$src/skills/$s" "$link"
            else
              if [ -e "$link" ]; then
                run mkdir -p ${home}/.agents/skills-replaced
                run mv "$link" "${home}/.agents/skills-replaced/$s.$(date +%Y%m%d%H%M%S)"
              fi
              run mkdir -p ${home}/.agents/skills
              run ln -s "$src/skills/$s" "$link"
            fi
            for h in ${home}/.pi/agent/skills ${home}/.claude/skills; do
              if [ -d "$h" ] && [ ! -e "$h/$s" ] && [ ! -L "$h/$s" ]; then
                run ln -s "$link" "$h/$s"
              fi
            done
          done
          agent=${home}/.pi/agent/agents/techwriter.md
          body="$(${pkgs.gawk}/bin/awk 'n >= 2 { print; next } /^---$/ { n++ }' "$src/agents/techwriter.agent.md")"
          if [ "$(cat ${techwriterHeader}; printf '%s\n' "$body")" != "$(cat "$agent" 2>/dev/null)" ]; then
            run mkdir -p ${home}/.pi/agent/agents
            if [ -z "''${DRY_RUN:-}" ]; then
              { cat ${techwriterHeader}; printf '%s\n' "$body"; } >"$agent.hm-tmp" && mv "$agent.hm-tmp" "$agent"
            else
              echo "would write $agent"
            fi
          fi
        fi
      '';
    };

    launchd.agents.chorus-pi-daemon = {
      enable = true;
      config = {
        Label = "com.dktaohan.chorus-pi-daemon";
        ProgramArguments = ["${chorusPiDaemon}/bin/chorus-pi-daemon"];
        EnvironmentVariables.HOME = home;
        RunAtLoad = true;
        KeepAlive = true;
        ThrottleInterval = 30;
        ProcessType = "Background";
        StandardOutPath = "${home}/.local/state/chorus-pi-daemon.log";
        StandardErrorPath = "${home}/.local/state/chorus-pi-daemon.log";
      };
    };
  };
}
