{gateway, ...}: {
  # pi on the token-saving toolchain, after LEGO/agentic-engineering-community
  # docs/guides/setup-token-saving-toolchain.md. That guide targets Claude
  # Code; every tool also ships a pi integration, which this wires:
  #   1 Caveman     proxy (launchd) + pi extension (through a shim) + skills
  #   2 RTK         rtk's own pi extension, generated by `rtk init --agent pi`
  #   3 ponytail    pi package (extension + skills)
  #   4 Signet      already team Signet (agent-integrations.nix)
  #   5 context-mode pi package + MCP server
  #   6 CodeGraph   MCP server
  #   8.5 Headroom  MCP server (container exec)
  #
  # A pi request then goes pi -> Caveman (127.0.0.1:8787) -> local-model-proxy
  # (127.0.0.1:18788, traces to Phoenix) -> Headroom (127.0.0.1:18787) ->
  # gateway /claude. The chain itself is in darwin.nix.
  den.aspects.dktaohan.homeManager = {
    pkgs,
    lib,
    config,
    ...
  }: let
    home = config.home.homeDirectory;
    entity = "M-02877";
    proxyUrl = gateway.proxy.loopbackUrl entity;
    proxyHostPort = lib.removePrefix "http://" proxyUrl;

    # Caveman's local proxy. Its port is the CLI's and the pi extension's
    # default gateway; headroom's 8787 is container-internal on this host,
    # so the two do not collide.
    cavemanListen = "127.0.0.1:8787";
    cavemanUrl = "http://${cavemanListen}";

    # The Caveman CLI and its native binaries come from npm
    # (@caveman-ai/cli, `caveman setup --install`), not Nix: ~/.caveman/bin.
    cavemanCli = "${home}/.local/bin/caveman";
    cavemanExtension = "${home}/.local/lib/node_modules/@caveman-ai/cli/dist/caveman-pi-extension.mjs";

    cavemanProxy = pkgs.writeShellApplication {
      name = "caveman-proxy-serve";
      text = ''
        bin=${lib.escapeShellArg "${home}/.caveman/bin/caveman-proxy"}
        if [ ! -x "$bin" ]; then
          echo "caveman-proxy-serve: $bin missing (run caveman setup --install); retrying" >&2
          sleep 60
          exit 1
        fi
        # The run-state file these write (~/.caveman/run/8787.json) is what the
        # pi extension reads to decide whether to compress:
        # - owner `start` marks a long-lived proxy, not a per-wrap one.
        # - CAVEMAN_RECOVERY=mcp says the agent can expand elided content. True
        #   for pi: the extension registers caveman_retrieve itself.
        # - CAVE_ENGINE_TOON re-encodes uniform JSON as TOON when that is
        #   smaller, as `caveman <agent>` does.
        # - The SSRF guard blocks loopback upstreams unless they are listed.
        export CAVEMAN_LISTEN=${cavemanListen}
        export CAVEMAN_PROXY_OWNER=start
        export CAVEMAN_MODE=compress
        export CAVEMAN_RECOVERY=mcp
        export CAVE_ENGINE_TOON=best-of
        export CAVE_SSRF_ALLOWLIST=${proxyHostPort}
        exec "$bin" serve
      '';
    };

    # Without this file the proxy's anthropic upstream is api.anthropic.com,
    # which would send the LEGO gateway key to Anthropic's public API.
    cavemanConfig = ''
      # Managed by den (modules/M-02877/token-toolchain.nix).
      providers:
        anthropic:
          base_url: ${proxyUrl}
    '';

    # Caveman's pi extension routes a model by re-registering its provider
    # with only a new baseUrl. pi then drops the provider's authHeader and
    # sends the key only as x-api-key, which the gateway rejects (401). So
    # the lego-claude provider points at Caveman itself, with authHeader
    # intact, and this shim makes the extension's provider (un)registration
    # a no-op. Everything else -- hooks, tool-output shrink, caveman_retrieve
    # -- is the extension's own. The trade-off: no pass-through when the
    # proxy is down, which KeepAlive below covers.
    cavemanShim = ''
      // Managed by den (modules/M-02877/token-toolchain.nix). Edits are overwritten.
      import { existsSync } from "node:fs";
      import { pathToFileURL } from "node:url";

      const upstream = ${builtins.toJSON cavemanExtension};
      process.env.CAVEMAN_PI_HOOK_CMD ??= JSON.stringify([${builtins.toJSON cavemanCli}]);

      export default async function (pi) {
        if (!existsSync(upstream)) {
          process.stderr.write("caveman: " + upstream + " missing; run `npm install -g @caveman-ai/cli`\n");
          return;
        }
        const { default: caveman } = await import(pathToFileURL(upstream).href);
        const shim = new Proxy(pi, {
          get(target, key) {
            if (key === "registerProvider" || key === "unregisterProvider") return () => {};
            const value = Reflect.get(target, key);
            return typeof value === "function" ? value.bind(target) : value;
          },
        });
        return caveman(shim);
      }
    '';

    # rtk ships its pi extension inside the binary; generate it from the same
    # rtk that is installed, so the two never drift.
    rtkPiExtension = pkgs.runCommand "rtk-pi-extension.ts" {} ''
      export HOME=$TMPDIR
      ${lib.getExe pkgs.rtk} init -g --agent pi >/dev/null
      cp "$HOME/.pi/agent/extensions/rtk.ts" "$out"
    '';

    cavemanSkills = ["caveman" "caveman-commit" "caveman-compress" "caveman-help" "caveman-review" "caveman-stats"];
  in {
    agentProviders.pi = {
      baseUrl = "${cavemanUrl}/w/pi";
      # pi sends the key both as the bearer and as x-api-key. Caveman forwards
      # only x-api-key when both arrive, and the gateway accepts only the
      # bearer. An empty x-api-key makes Caveman forward the bearer.
      headers."x-api-key" = "";
    };

    piAgent = {
      packages = [
        # Not npm:ponytail, which is an unrelated package.
        "npm:@dietrichgebert/ponytail@4.13.0"
        "npm:context-mode@1.0.169"
      ];
      mcpServers = {
        context-mode = {
          command = "${home}/.pi/agent/npm/node_modules/.bin/context-mode";
          description = "context-mode: sandboxed tool output and a per-project FTS5 session knowledge base";
        };
        codegraph = {
          command = "/opt/homebrew/bin/codegraph";
          args = ["serve" "--mcp"];
          description = "CodeGraph: symbol-level codebase index";
        };
        # Inside the container, headroom listens on its container port.
        headroom = {
          command = "/opt/homebrew/bin/container";
          args = ["exec" "-i" "headroom" "headroom" "mcp" "serve" "--proxy-url" "http://127.0.0.1:${toString gateway.headroom.containerPort}"];
          description = "Headroom compression stats and controls";
        };
      };
    };

    home.file = {
      ".caveman/caveman.yaml".text = cavemanConfig;
      ".pi/agent/extensions/caveman.js".text = cavemanShim;
      ".pi/agent/extensions/rtk.ts".source = rtkPiExtension;
    };

    home.activation = {
      # New pi sessions start on lego-claude. Only set when nothing is chosen,
      # so a default picked later in pi is kept; running sessions keep the
      # provider they started with.
      piDefaultProvider = lib.hm.dag.entryAfter ["writeBoundary" "piPackages"] ''
        settings=${lib.escapeShellArg "${home}/.pi/agent/settings.json"}
        if [ -e "$settings" ] && [ -z "$(${lib.getExe pkgs.jq} -r '.defaultProvider // empty' "$settings")" ]; then
          if merged="$(${lib.getExe pkgs.jq} --arg m ${lib.escapeShellArg gateway.modelIds.opus} \
              '.defaultProvider = "lego-claude" | .defaultModel = $m' "$settings")"; then
            if [ -z "''${DRY_RUN:-}" ]; then
              (umask 077 && printf '%s\n' "$merged" >"$settings.hm-tmp") && mv "$settings.hm-tmp" "$settings"
            else
              echo "would set defaultProvider in $settings"
            fi
          fi
        fi
      '';

      # Caveman's skills come from its own installer into ~/.claude/skills;
      # link them for pi rather than copying, so `caveman` updates reach both.
      piCavemanSkills = lib.hm.dag.entryAfter ["writeBoundary"] ''
        for s in ${lib.escapeShellArgs cavemanSkills}; do
          src=${lib.escapeShellArg "${home}/.claude/skills"}/$s
          dst=${lib.escapeShellArg "${home}/.pi/agent/skills"}/$s
          if [ -d "$src" ] && [ ! -e "$dst" ] && [ ! -L "$dst" ]; then
            run mkdir -p ${lib.escapeShellArg "${home}/.pi/agent/skills"}
            run ln -s "$src" "$dst"
          fi
        done
      '';
    };

    launchd.agents.caveman-proxy = {
      enable = true;
      config = {
        Label = "com.dktaohan.caveman-proxy";
        ProgramArguments = ["${cavemanProxy}/bin/caveman-proxy-serve"];
        EnvironmentVariables.HOME = home;
        WorkingDirectory = "${home}/.caveman";
        RunAtLoad = true;
        KeepAlive = true;
        ThrottleInterval = 10;
        ProcessType = "Background";
        StandardOutPath = "${home}/.local/state/caveman-proxy.log";
        StandardErrorPath = "${home}/.local/state/caveman-proxy.log";
      };
    };
  };
}
